Repository controlplaneio-fluxcd/distribution, pull requests merged in 2024-12, with the labels that each got.

#127 chore: fix typo in the distribution website
  docs/distribution/index.md
Labels: documentation

#130 Run conformance tests for Kubernetes 1.32.0
  .github/workflows/e2e-fips.yaml
  .github/workflows/e2e.yaml
Labels: area/testing

#133 Add job to scan flux-operator in the Vulnerability scan workflow
  .github/workflows/scan-distribution.yaml
Labels: area/actions

#126 docs: Add Generic Helm Chart guide
  docs/guides/flux-generic-helm-chart.md
  docs/marketplace/aws.md
  mkdocs.yml
Labels: documentation

#136 Update Flux Operator docs to v0.11.0
  docs/operator/flux-config.md
  docs/operator/fluxinstance.md
  docs/releases/release-v2.4.md
  releases/release-v2.4.md
Labels: documentation
