Repository controlplaneio-fluxcd/distribution, pull requests merged in 2025-09, with the labels that each got.

#242 actions/push: Improve `pushed` output docs
  actions/push/README.md
Labels: documentation, area/actions

#251 ci: add support for source-watcher
  .github/workflows/e2e-fips.yaml
  .github/workflows/e2e.yaml
  .github/workflows/export-images.sh
  .github/workflows/scan-controllers.yaml
  .github/workflows/update-images.sh
  .github/workflows/update-images.yaml
Labels: enhancement

#252 docs: Using ResourceSets for Image Update Automation
  docs/operator/resourcesets/image-automation.md
  mkdocs.yml
Labels: documentation
