Repository controlplaneio-fluxcd/distribution, pull requests merged in 2025-04, with the labels that each got.

#180 Publish Flux D2 Architectural Reference
  docs/guides/d2-architecture-reference.md
  guides/ControlPlane_Flux_D2_Reference_Architecture_Guide.pdf
  mkdocs.yml
Labels: documentation

#187 vex: Add exception for CVE-2025-29087
  .trivyignore
  vex/v2.5.json
Labels: area/cves, area/vex

#190 Run conformance tests for Kubernetes 1.33.0
  .github/workflows/e2e-fips.yaml
  .github/workflows/e2e.yaml
  docs/releases/release-v2.5.md
  releases/release-v2.5.md
Labels: area/testing
